### ISSUE TITLE
Drop the Ubuntu 14.04 archive

### ISSUE THREAD

**Issue by linkmauve** [flathub/io.missioncenter.MissionCenter#14]
The GNOME SDK you are using already provides a base distribution, you shouldn’t need an unmaintained obsolete additional base system.

**Comment by kicsyromy** [comment]
The Gatherer, a binary that is run outside of the sandbox, needs to maintain compatibility with an old version of `glibc` and `musl libc`, to ensure compatibility with a wide range of Linux distrubutions.

I use Ubuntu 14.04 and Apline 3.7 since they are so old, virtually no one should use them. They are only used as a `rootfs` to build the Gatherer, nothing is shipped from those distributions.
